language: node

node_js:
  - '12'

addons:
  apt:
    update: true

jobs:
  include:
    - stage: Tests
      os: linux
      dist: bionic
      script:
        - npm install

    - stage: Packages for macOS
      if: tag IS present
      os: osx
      osx_image: xcode11
      script:
        - npm install
        - npm run package-darwin
        - npm run installer-darwin

    - stage: Packages for linux
      if: tag IS present
      os: linux
      dist: bionic
      script:
        - sudo apt-get install -y fakeroot rpm
        - npm install
        - npm run package-linux
        - npm run installer-debian
        - npm run installer-redhat

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - builds/Monday-darwin-x64.dmg
    - builds/monday_${TRAVIS_TAG}_amd64.deb
    - builds/Monday-${TRAVIS_TAG}-1.amd64.rpm
  on:
    repo: eko/monday-app
    tags: true
