language: node

node_js:
  - '12'

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run package

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - builds/Monday-darwin-x64.dmg
  on:
    repo: eko/monday-app
    tags: true
