language: node

node_js:
  - '12'

addons:
  apt:
    update: true

jobs:
  include:
    - stage: Tests
      os: linux
      dist: bionic
      script:
        - npm run test

    - stage: Packages for macOS
      if: tag IS present
      os: osx
      osx_image: xcode11
      script:
        - npm install
        - npm rebuild --build-from-source=grpc --target=6.0.0 --runtime=electron --dist-url=https://atom.io/download/electron # Needed by Electron to work with gRPC
        - npm run build
        - npm run package-darwin
        - npm rebuild --build-from-source=macos-alias
        - npm run installer-darwin
        - npm run installer-darwin-zip

    - stage: Packages for linux
      if: tag IS present
      os: linux
      dist: bionic
      script:
        - sudo apt-get install -y fakeroot rpm
        - npm install
        - npm rebuild --build-from-source=grpc --target=6.0.0 --runtime=electron --dist-url=https://atom.io/download/electron # Needed by Electron to work with gRPC
        - npm run build
        - npm run package-linux
        - npm rebuild --build-from-source=macos-alias
        - npm run installer-linux-zip
        - npm run installer-debian
        - npm run installer-redhat

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - builds/Monday-darwin-x64.dmg
    - builds/Monday-darwin-x64.zip
    - builds/Monday-linux-x64.zip
    - builds/monday_${TRAVIS_TAG}_amd64.deb
    - builds/Monday-${TRAVIS_TAG}-1.amd64.rpm
  on:
    repo: eko/monday-app
    tags: true
