// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monday.proto

package monday

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5b49cb27e638a9, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProjectsResponse) Reset()         { *m = GetProjectsResponse{} }
func (m *GetProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectsResponse) ProtoMessage()    {}
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5b49cb27e638a9, []int{1}
}

func (m *GetProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsResponse.Unmarshal(m, b)
}
func (m *GetProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsResponse.Merge(m, src)
}
func (m *GetProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectsResponse.Size(m)
}
func (m *GetProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsResponse proto.InternalMessageInfo

func (m *GetProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type Project struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a5b49cb27e638a9, []int{2}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "monday.Empty")
	proto.RegisterType((*GetProjectsResponse)(nil), "monday.GetProjectsResponse")
	proto.RegisterType((*Project)(nil), "monday.Project")
}

func init() { proto.RegisterFile("monday.proto", fileDescriptor_1a5b49cb27e638a9) }

var fileDescriptor_1a5b49cb27e638a9 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0xcf, 0x4b,
	0x49, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xd8, 0xb9, 0x58,
	0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0x9c, 0xb8, 0x84, 0xdd, 0x53, 0x4b, 0x02, 0x8a, 0xf2, 0xb3,
	0x52, 0x93, 0x4b, 0x8a, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xb4, 0xb9, 0x38,
	0x0a, 0xa0, 0x62, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xfc, 0x7a, 0x50, 0x83, 0xa0, 0x6a,
	0x83, 0xe0, 0x0a, 0x94, 0x64, 0xb9, 0xd8, 0xa1, 0x82, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x51, 0x1b, 0x23, 0x17, 0xaf, 0x2f,
	0x58, 0x6f, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x35, 0x17, 0x37, 0x92, 0xa5, 0x42,
	0xbc, 0x30, 0xa3, 0xc1, 0x4e, 0x92, 0x92, 0x86, 0x71, 0xb1, 0x38, 0x4c, 0x89, 0x41, 0xc8, 0x82,
	0x4b, 0xcc, 0xbf, 0x20, 0x35, 0xcf, 0x39, 0x3f, 0x2f, 0x2d, 0x33, 0xbd, 0xb4, 0x28, 0xb1, 0x24,
	0x33, 0x3f, 0xcf, 0x2d, 0x33, 0x27, 0x15, 0xc3, 0x1c, 0x54, 0xae, 0x12, 0x43, 0x12, 0x1b, 0x38,
	0x0c, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x27, 0x2d, 0xcf, 0xb1, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MondayServiceClient is the client API for MondayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MondayServiceClient interface {
	GetProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	OpenConfigurationFiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type mondayServiceClient struct {
	cc *grpc.ClientConn
}

func NewMondayServiceClient(cc *grpc.ClientConn) MondayServiceClient {
	return &mondayServiceClient{cc}
}

func (c *mondayServiceClient) GetProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/monday.MondayService/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mondayServiceClient) OpenConfigurationFiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/monday.MondayService/OpenConfigurationFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MondayServiceServer is the server API for MondayService service.
type MondayServiceServer interface {
	GetProjects(context.Context, *Empty) (*GetProjectsResponse, error)
	OpenConfigurationFiles(context.Context, *Empty) (*Empty, error)
}

func RegisterMondayServiceServer(s *grpc.Server, srv MondayServiceServer) {
	s.RegisterService(&_MondayService_serviceDesc, srv)
}

func _MondayService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MondayServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monday.MondayService/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MondayServiceServer).GetProjects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MondayService_OpenConfigurationFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MondayServiceServer).OpenConfigurationFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monday.MondayService/OpenConfigurationFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MondayServiceServer).OpenConfigurationFiles(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MondayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monday.MondayService",
	HandlerType: (*MondayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _MondayService_GetProjects_Handler,
		},
		{
			MethodName: "OpenConfigurationFiles",
			Handler:    _MondayService_OpenConfigurationFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monday.proto",
}
